//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Duck
{
	public virtual void Quack()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Swim()
	{
		throw new System.NotImplementedException();
	}

	public abstract void Display();

}

