//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// //se muestra como un Pato Mallard
/// 
/// </remarks>
public class MallardDuck : Duck
{
	public override void Display()
	{
		throw new System.NotImplementedException();
	}

}

