//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FactoriaConcreta1 : FactoriaAbstracta
{
	public virtual void CrearProductoA()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CrearProductoB()
	{
		throw new System.NotImplementedException();
	}

}

